general {
    col.active_border = rgb(B91C1C)
    # gaps_in = 4
    # gaps_out = 6
}

decoration {
    active_opacity = 0.90
    inactive_opacity = 0.80
    rounding = 8

    blur {
        enabled = yes
        size = 4
        passes = 3
        ignore_opacity = true

        noise = 0.1
        contrast = 1.5
        xray = false
        new_optimizations = true
    }
}

animations {
    enabled = true
    bezier = easing, 0.25, 1, 0.5, 1

    animation = workspaces, 1, 6, easing, slide
    animation = windows, 1, 6, easing, popin
}

# waybar layer
layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0.5

# walker layer || app launcher
layerrule = match:namespace walker, blur on
layerrule = match:namespace walker, ignore_alpha 0.5

# mako || notifications
layerrule = match:namespace mako, blur on
layerrule = match:namespace mako, ignore_alpha 0.5

# custom bindings 
bindd = SUPER ALT, P, HyprPicker, exec, hyprpicker -a
bindd = SUPER ALT, T, Text Extract, exec, omarchy-capture-text-extraction
bindd = SUPER, Q, Close Window, killactive,
