foreground #bebebe
background #121212
selection_foreground #bebebe
selection_background #333333

cursor #B91C1C
cursor_text_color #121212

active_border_color #A00000
active_tab_background #A00000

color0 #333333
color1 #A00000
color2 #FF0000
color3 #A00000
color4 #ff8181
color5 #D35F5F
color6 #bebebe
color7 #bebebe
color8 #8a8a8d
color9 #B91C1C
color10 #FF0000
color11 #A00000
color12 #ff8181
color13 #B91C1C
color14 #eaeaea
color15 #ffffff


cursor_trail 5
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
cursor_blink_interval 1
